#!/usr/bin/env bash
#Change IP address for local and facebook

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1s/^/8.8.8.8    facebook.com\n/' ~/hosts.new
cat ~/hosts.new > /etc/hosts
